#! /bin/sh
# Install modified versions of certain ANSI-incompatible system header files
# which are fixed to work correctly with ANSI C
# and placed in a directory that GNU C will search.
# This works properly on a Sun in system version 3.4;
# for other versions, you had better check.

mkdir /usr/local/lib/gcc-include
for dir in sys sun sundev sunwindow; do
  if [ -d /usr/include/$dir ]; then
    mkdir /usr/local/lib/gcc-include/$dir
  fi
done

cp /usr/include/sys/ioctl.h /usr/local/lib/gcc-include/sys/ioctl.h
chmod +w /usr/local/lib/gcc-include/sys/ioctl.h
ex /usr/local/lib/gcc-include/sys/ioctl.h <<EOF
g/_IO/s/(\(.\),/('\1',/
g/#define._IO/s/'x'/x/g
wq
EOF

for file in sys/mtio.h sys/vcmd.h sys/des.h  \
	    vaxuba/qvioctl.h \
	    sun/dkio.h sun/fbio.h sun/gpio.h sun/ndio.h  \
            sundev/kbio.h sundev/msio.h sundev/fpareg.h sundev/mcpcmd.h  \
	    sundev/msreg.h sundev/vuid_event.h sunwindow/win_ioctl.h; do
  if [ -r /usr/include/$file ]; then
    cp /usr/include/$file /usr/local/lib/gcc-include/$file
    chmod +w /usr/local/lib/gcc-include/$file
    ex /usr/local/lib/gcc-include/$file <<EOF
    g/_IO/s/(\(.\),/('\1',/
    wq
EOF
  fi
done

cp /usr/include/sys/ttychars.h /usr/local/lib/gcc-include/sys/ttychars.h
chmod +w /usr/local/lib/gcc-include/sys/ttychars.h
ex /usr/local/lib/gcc-include/sys/ttychars.h << EOF
g/CTRL/s/(\(.\))/('\1')/
g/#define.CTRL/s/'c'/c/g
wq
EOF
